"""Student Pass/Fail Predictor.

A beginner Machine Learning application using DecisionTreeClassifier to predict whether a student passes or fails.
Supports both Streamlit Web Interface and Command-Line Interface.
"""

import sys
import argparse
from pathlib import Path
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

BASE_DIR = Path(__file__).resolve().parent
DATA_PATH = BASE_DIR / "data" / "student_performance.csv"


def train_model():
    """Load performance CSV dataset and train a Decision Tree classifier."""
    if not DATA_PATH.exists():
        raise FileNotFoundError(f"Dataset file missing at: {DATA_PATH}")
        
    data = pd.read_csv(DATA_PATH)
    features = ["study_hours", "attendance", "previous_score", "assignments_completed"]
    X = data[features]
    y = data["result"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=42, stratify=y
    )
    
    # Decision Tree classifier with max_depth=4 to prevent overfitting
    model = DecisionTreeClassifier(max_depth=4, random_state=42)
    model.fit(X_train, y_train)
    
    acc = accuracy_score(y_test, model.predict(X_test))
    return model, acc, data


MODEL, MODEL_ACCURACY, DATASET = train_model()


def validate_values(study_hours: float, attendance: float, previous_score: float, assignments: int):
    """Validate numerical input ranges."""
    if not (0 <= study_hours <= 24):
        raise ValueError("Daily study hours must be between 0 and 24.")
    if not (0 <= attendance <= 100):
        raise ValueError("Attendance percentage must be between 0% and 100%.")
    if not (0 <= previous_score <= 100):
        raise ValueError("Previous score percentage must be between 0% and 100%.")
    if not (0 <= assignments <= 20):
        raise ValueError("Assignments completed must be between 0 and 20.")


def predict_result(study_hours: float, attendance: float, previous_score: float, assignments: int):
    """Predict Pass/Fail while enforcing minimum academic eligibility rules."""
    validate_values(study_hours, attendance, previous_score, assignments)

    # Minimum eligibility rule checks
    if attendance < 75.0:
        return "Fail", 100.0, "Attendance is below the mandatory 75% requirement."
    if study_hours < 2.0:
        return "Fail", 100.0, "Daily study time is below the 2-hour minimum requirement."

    sample = pd.DataFrame(
        [[study_hours, attendance, previous_score, assignments]],
        columns=["study_hours", "attendance", "previous_score", "assignments_completed"],
    )
    
    pred = MODEL.predict(sample)[0]
    probabilities = MODEL.predict_proba(sample)[0]
    confidence = max(probabilities) * 100

    return pred, confidence, "Prediction generated by Decision Tree Classifier."


def run_cli():
    """Run CLI interface."""
    parser = argparse.ArgumentParser(description="Predict student pass or fail outcome.")
    parser.add_argument("--study-hours", type=float, help="Daily study hours (e.g. 6.0)")
    parser.add_argument("--attendance", type=float, help="Attendance % (e.g. 85.0)")
    parser.add_argument("--previous-score", type=float, help="Previous grade % (e.g. 78.0)")
    parser.add_argument("--assignments-completed", type=int, help="Completed assignments (e.g. 9)")
    
    args = parser.parse_args()
    provided = [args.study_hours, args.attendance, args.previous_score, args.assignments_completed]

    if any(v is not None for v in provided):
        if any(v is None for v in provided):
            parser.error("Must provide all 4 parameters or run without arguments for interactive CLI.")
        study_h, att, prev_s, assign = args.study_hours, args.attendance, args.previous_score, args.assignments_completed
    else:
        print("--- 🎓 Student Pass/Fail Predictor CLI ---")
        study_h = float(input("Daily study hours: "))
        att = float(input("Attendance percentage: "))
        prev_s = float(input("Previous score percentage: "))
        assign = int(input("Assignments completed: "))

    try:
        result, conf, reason = predict_result(study_h, att, prev_s, assign)
        print(f"\nPrediction: [{result}]")
        print(f"Confidence: {conf:.1f}%")
        print(f"Reason: {reason}")
        print(f"Model Test Accuracy: {MODEL_ACCURACY:.1%}")
    except ValueError as err:
        print(f"Input Error: {err}")


def run_streamlit():
    """Run Streamlit Web GUI interface."""
    import streamlit as st

    st.set_page_config(page_title="Student Pass/Fail Predictor", page_icon="🎓", layout="centered")

    st.title("🎓 Student Pass/Fail Predictor")
    st.write("A beginner Machine Learning project using a **Decision Tree Classifier** to evaluate student academic performance.")

    st.markdown("---")
    st.subheader("📊 Enter Student Attributes")

    col1, col2 = st.columns(2)
    with col1:
        study_hours = st.slider("Daily Study Hours:", 0.0, 16.0, 6.0, 0.5)
        attendance = st.slider("Attendance Percentage (%):", 0.0, 100.0, 85.0, 1.0)
    with col2:
        previous_score = st.slider("Previous Test Score (%):", 0.0, 100.0, 75.0, 1.0)
        assignments = st.slider("Assignments Completed:", 0, 20, 10, 1)

    if st.button("Predict Outcome", type="primary"):
        result, confidence, explanation = predict_result(study_hours, attendance, previous_score, assignments)

        st.markdown("### 🎯 Result")
        if result == "Pass":
            st.success(f"🎉 **PREDICTION: PASS** (Confidence: {confidence:.1f}%)")
        else:
            st.error(f"⚠️ **PREDICTION: FAIL** (Confidence: {confidence:.1f}%)")

        st.info(f"**Explanation:** {explanation}")
        st.caption(f"Model Validation Accuracy on Demo Dataset: {MODEL_ACCURACY:.1%}")


if __name__ == "__main__":
    # Check if running via streamlit
    if "streamlit" in sys.modules or (len(sys.argv) > 1 and sys.argv[1].endswith(".py")):
        try:
            import streamlit as st
            run_streamlit()
        except ImportError:
            run_cli()
    else:
        run_cli()
